<?php

namespace MultiMaps;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-06 at 15:08:31.
 */
class BoundsTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Bounds
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Bounds;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers MultiMaps\Bounds::getCenter
	 * @todo   Implement testGetCenter().
	 */
	public function testGetCenterAndExtend() {
		$this->assertEquals( $this->object->getCenter(), false);

		$point = new Point(10, 2);
		$this->object->extend( array($point) );
		$this->assertEquals( $this->object->getCenter(), $point );

		$this->object->extend( array(new Point(20, 1)) );
		$this->assertEquals( $this->object->getCenter(), new Point(15, 1.5) );

		$this->assertEquals( $this->object->getData(), array(
			'ne' => array( 'lat' => 20, 'lon' => 2 ),
			'sw' => array( 'lat' => 10, 'lon' => 1 ),
			) );
	}

	/**
	 * @covers MultiMaps\Bounds::isValid
	 * @todo   Implement testIsValid().
	 */
	public function testIsValid() {
		$this->assertEquals( $this->object->isValid(), false);

		$this->object->extend( array(new Point(14, 41)) );

		$this->assertEquals( $this->object->isValid(), true);
	}

}
