<?php

namespace MultiMaps;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-30 at 09:48:20.
 */
class LeafletTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Leaflet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Leaflet();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }


    public function testParseOneMarker() {
        $this->object->parse(
                array(
                    "55.7557860, 37.6176330",
                    "service=leaflet",
                    )
                );
        $this->assertEquals(
                \FormatJson::encode( $this->object->getMapData( array("55.7557860, 37.6176330", "service=leaflet") ) ),
                '{"markers":[{"pos":[{"lat":55.755786,"lon":37.617633}]}],"zoom":14,"center":{"lat":55.755786,"lon":37.617633}}'
                );

    }

}
