<?php

namespace MultiMaps;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-30 at 09:48:20.
 */
class LeafletTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Leaflet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Leaflet();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }


    public function testParseOneMarker() {
        $this->assertEquals(
                \FormatJson::encode( $this->object->getMapData( array('55.7557860, 37.6176330', 'service=leaflet') ) ),
                '{"markers":[{"pos":[{"lat":55.755786,"lon":37.617633}]}],"zoom":14,"center":{"lat":55.755786,"lon":37.617633}}'
                );
    }

    public function testParseOneLine() {
        $this->assertEquals(
                \FormatJson::encode( $this->object->getMapData( array(' ', 'lines = 53.225768435790194 , 23.466796875 : 53.9560855309879,29.1796875', 'service=leaflet') ) ),
                '{"lines":[{"pos":[{"lat":53.22576843579,"lon":23.466796875},{"lat":53.956085530988,"lon":29.1796875}]}],"bounds":{"ne":{"lat":53.956085530988,"lon":29.1796875},"sw":{"lat":53.22576843579,"lon":23.466796875}}}'
                );
    }

    public function testParseOnePolygon() {
        $this->assertEquals(
                \FormatJson::encode( $this->object->getMapData( array(' ', 'polygons=  62.103882522897855,   5.09765625 :   58.309488840677645,5.712890625 : 58.95000823335702,10.8984375', 'service=leaflet') ) ),
                '{"polygons":[{"pos":[{"lat":62.103882522898,"lon":5.09765625},{"lat":58.309488840678,"lon":5.712890625},{"lat":58.950008233357,"lon":10.8984375}]}],"bounds":{"ne":{"lat":62.103882522898,"lon":10.8984375},"sw":{"lat":58.309488840678,"lon":5.09765625}}}'
                );
    }

    public function testParseOneRectangle() {
        $this->assertEquals(
                \FormatJson::encode( $this->object->getMapData( array(' ', 'rectangles  =51.83577752045248  ,33.837890625 : 46.37725420510028 ,23.37890625 ') ) ),
                '{"rectangles":[{"pos":[{"lat":51.835777520452,"lon":33.837890625},{"lat":46.3772542051,"lon":23.37890625}]}],"bounds":{"ne":{"lat":51.835777520452,"lon":33.837890625},"sw":{"lat":46.3772542051,"lon":23.37890625}}}'
                );
    }

}
